"""empty message

Revision ID: b7628a389f12
Revises: 
Create Date: 2018-04-15 11:23:28.744404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7628a389f12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('util_name_ukr', sa.String(length=140), nullable=True),
    sa.Column('util_name_rus', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('util_name_rus'),
    sa.UniqueConstraint('util_name_ukr')
    )
    op.drop_column('team', 'position')
    op.drop_column('team', 'positiin')
    op.drop_column('team', 'full_name')
    op.drop_column('video', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('slug', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('full_name', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('positiin', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('position', sa.VARCHAR(length=140), nullable=True))
    op.drop_table('utils')
    # ### end Alembic commands ###
