"""empty message

Revision ID: bda832dc0b63
Revises: 
Create Date: 2018-04-10 23:47:11.709774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda832dc0b63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'position')
    op.drop_column('team', 'full_name')
    op.drop_column('team', 'positiin')
    op.drop_column('video', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('slug', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('positiin', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('full_name', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('position', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
