"""empty message

Revision ID: bdf0e9a37cad
Revises: 
Create Date: 2018-06-06 19:40:36.771724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf0e9a37cad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videotags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('videotag')
    op.create_foreign_key(None, 'video', 'videotags', ['videotag_id'], ['id'])
    op.drop_column('video', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('slug', sa.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.create_table('videotag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.drop_table('videotags')
    # ### end Alembic commands ###
