"""empty message

Revision ID: c3183f666488
Revises: 
Create Date: 2018-04-17 12:35:51.703042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3183f666488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_ukr', sa.String(length=140), nullable=True),
    sa.Column('position_rus', sa.String(length=140), nullable=True),
    sa.Column('full_name_ukr', sa.String(length=140), nullable=True),
    sa.Column('full_name_rus', sa.String(length=140), nullable=True),
    sa.Column('img_name', sa.String(length=140), nullable=True),
    sa.Column('phone', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('img_name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_column('team', 'full_name')
    op.drop_column('team', 'position')
    op.drop_column('team', 'positiin')
    op.drop_column('video', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('slug', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('positiin', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('position', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('full_name', sa.VARCHAR(length=140), nullable=True))
    op.drop_table('roles_users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
