"""empty message

Revision ID: dddbe84ac704
Revises: 
Create Date: 2018-04-16 21:18:08.204283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddbe84ac704'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pub_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_name_ukr', sa.String(length=140), nullable=True),
    sa.Column('doc_name_rus', sa.String(length=140), nullable=True),
    sa.Column('img_name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_name_rus'),
    sa.UniqueConstraint('doc_name_ukr')
    )
    op.add_column('team', sa.Column('email', sa.String(length=140), nullable=True))
    op.drop_column('team', 'full_name')
    op.drop_column('team', 'position')
    op.drop_column('team', 'positiin')
    op.drop_column('video', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('slug', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('positiin', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('position', sa.VARCHAR(length=140), nullable=True))
    op.add_column('team', sa.Column('full_name', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('team', 'email')
    op.drop_table('pub_info')
    # ### end Alembic commands ###
