"""empty message

Revision ID: fd92f8a59772
Revises: 
Create Date: 2018-04-20 13:02:19.818250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd92f8a59772'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servtypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ukr', sa.String(length=140), nullable=True),
    sa.Column('name_rus', sa.String(length=140), nullable=True),
    sa.Column('img_name', sa.String(length=140), nullable=True),
    sa.Column('servtype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['servtype_id'], ['servtypes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_rus'),
    sa.UniqueConstraint('name_ukr')
    )
    op.drop_table('utils')
    op.drop_table('team')
    op.drop_table('pub_info')
    op.drop_column('video', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('slug', sa.VARCHAR(length=140), nullable=True))
    op.create_table('pub_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doc_name_ukr', sa.VARCHAR(length=140), nullable=True),
    sa.Column('doc_name_rus', sa.VARCHAR(length=140), nullable=True),
    sa.Column('img_name', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_name_rus'),
    sa.UniqueConstraint('doc_name_ukr')
    )
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('positiin', sa.VARCHAR(length=140), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('img_name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('position', sa.VARCHAR(length=140), nullable=True),
    sa.Column('full_name_rus', sa.VARCHAR(length=140), nullable=True),
    sa.Column('full_name_ukr', sa.VARCHAR(length=140), nullable=True),
    sa.Column('position_rus', sa.VARCHAR(length=140), nullable=True),
    sa.Column('position_ukr', sa.VARCHAR(length=140), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utils',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('util_name_ukr', sa.VARCHAR(length=140), nullable=True),
    sa.Column('util_name_rus', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('util_name_rus'),
    sa.UniqueConstraint('util_name_ukr')
    )
    op.drop_table('services')
    op.drop_table('servtypes')
    # ### end Alembic commands ###
